baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tommy Dittberner"
paginate = 6

[params]
#  titleEmoji = "ðŸ‘‹"
  [params.socialOptions]
    github = "https://github.com/tommydittberner"
    twitter = "https://twitter.com/TommyDittberner"
    email = "todi@tuta.io"
    youtube = "https://youtube.com/kimahrey"

[[menu.header]]
name = "About"
url = "/about/"
weight = 100

[[menu.header]]
name = "Tags"
url = "/tags/"
weight = 10

[[menu.footer]]
name = "RSS"
url = "/index.xml"

[markup.highlight]
noClasses = false
lineNos = true

[markup.goldmark.renderer]
unsafe = true


